### ISSUE TITLE
Проверка 24310

### ISSUE THREAD

**Issue by NickO-O** [Anton-beep/distributed_calculations_go#3]
- Оцените проект согласно критериям
Необходимые требования:Существует Readme документ, в котором описано, как запустить систему и как ей пользоваться; Это может быть docker-compose, makefile, подробная инструкция - на ваш вкус. Если вы предоставляете только http-api, то - в Readme описаны примеры запросов с помощью curl-a или любым дргуми понятными образом - примеры полны и понятно как их запустить: **10**

- Программа запускается и все примеры с вычислением арифметических выражений корректно работают:  **10**

- Программа запускается и выполняются произвольные примеры с вычислением арифметических выражений:  **10**

- Можно перезапустить любой компонент системы и система корректно обработает перезапуск (результаты сохранены, система продолжает работать) :  **10**

- Система предосталяет графический интерфейс для вычисления арифметических выражений : **10**

- Реализован мониторинг воркеров:  **20**

- Реализован интерфейс для мориторинга воркеров: **10**

- Вам понятна кодовая база и структура проекта: **10**

- У системы есть документация со схемами, которая наглядно отвечает на вопрос: Как это все работает: **10**

- Выражение должно иметь возможность выполняться разными агентами:  **0**

**Comment by Anton-beep** [comment]
В `README.md` были описаны способы запуска дополнительных агентов. Не смотря на это, *я добавил дополнительный пункт с запуском второго агента во всех местах, где описан запуск программмы.*
Вот так выглядит работа нескольких агентов:
![expressions](https://github.com/Anton-beep/distributed_calculations_go/assets/61536762/6ac097ea-7db0-4549-9f63-c12d88928479)
![computingPowers](https://github.com/Anton-beep/distributed_calculations_go/assets/61536762/7c4e6e5c-5bdf-4260-b3ab-28f587534435)

Колонка статус была добавлена по требованию другой проверки
